
package ws.blackjack;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BlackJackWebService", targetNamespace = "http://blackjack.ws/", wsdlLocation = "file:/D:/JAVAMTA/BlackJackClientServer/BlackJackServer/src/conf/xml-resources/web-services/NewWebServiceFromWSDL/wsdl/BlackJackWebService.wsdl")
public class BlackJackWebService_Service
    extends Service
{

    private final static URL BLACKJACKWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException BLACKJACKWEBSERVICE_EXCEPTION;
    private final static QName BLACKJACKWEBSERVICE_QNAME = new QName("http://blackjack.ws/", "BlackJackWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/JAVAMTA/BlackJackClientServer/BlackJackServer/src/conf/xml-resources/web-services/NewWebServiceFromWSDL/wsdl/BlackJackWebService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BLACKJACKWEBSERVICE_WSDL_LOCATION = url;
        BLACKJACKWEBSERVICE_EXCEPTION = e;
    }

    public BlackJackWebService_Service() {
        super(__getWsdlLocation(), BLACKJACKWEBSERVICE_QNAME);
    }

    public BlackJackWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BLACKJACKWEBSERVICE_QNAME, features);
    }

    public BlackJackWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, BLACKJACKWEBSERVICE_QNAME);
    }

    public BlackJackWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BLACKJACKWEBSERVICE_QNAME, features);
    }

    public BlackJackWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BlackJackWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BlackJackWebService
     */
    @WebEndpoint(name = "BlackJackWebServicePort")
    public BlackJackWebService getBlackJackWebServicePort() {
        return super.getPort(new QName("http://blackjack.ws/", "BlackJackWebServicePort"), BlackJackWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BlackJackWebService
     */
    @WebEndpoint(name = "BlackJackWebServicePort")
    public BlackJackWebService getBlackJackWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://blackjack.ws/", "BlackJackWebServicePort"), BlackJackWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BLACKJACKWEBSERVICE_EXCEPTION!= null) {
            throw BLACKJACKWEBSERVICE_EXCEPTION;
        }
        return BLACKJACKWEBSERVICE_WSDL_LOCATION;
    }

}
