
package ws.blackjack;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "DuplicateGameName", targetNamespace = "http://blackjack.ws/")
public class DuplicateGameName_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DuplicateGameName faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public DuplicateGameName_Exception(String message, DuplicateGameName faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public DuplicateGameName_Exception(String message, DuplicateGameName faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ws.blackjack.DuplicateGameName
     */
    public DuplicateGameName getFaultInfo() {
        return faultInfo;
    }

}
